--hOMEWORK LESSON7
SELECT*FROM pRODUCTS
SELECT MIN (PRICE) FROM PRODUCTS
SELECT * FROM EMPLOYEES
SELECT MAX (SALARY) FROM EMPLOYEES
SELECT COUNT(*) FROM CUSTOMERS
SELECT COUNT (DISTINCT CATEGORY) FROM PRODUCTS
SELECT DISTINCT NAME, SUM (PRICE) FROM PRODUCTS GROUP BY NAME
SELECT AVG(AGE) FROM EMPLOYEES -- NO COLUMN NAME 'AGE' IN TABLE EMPLOYEES
SELECT DEPARTMENTID,COUNT (EMPLOYEEID) FROM EMPLOYEES GROUP BY DEPARTMENTID
SELECT CATEGORY,MIN(PRICE), MAX(PRICE) FROM PRODUCTS GROUP BY CATEGORY
SELECT * FROM SALES -- Invalid object name 'SALES'.
SELECT SUM (SALES) FROM SALES GROUP BY REGION
SELECT * FROM EMPLOYEES
SELECT DEPARTMENTID, COUNT(EMPLOYEEID) FROM EMPLOYEES GROUP BY 
DEPARTMENTID HAVING SUM(EMPLOYEEID)>=5
SELECT PRODUCT,SUM(SALES),AVG(SALES) 
FROM SALES GROUP BY PRODUCT --Invalid object name 'SALES'
SELECT DISTINCT JOBTITLE,COUNT (COLUMNAME) FROM EMPLOYEES GROUP BY JOBTITLE -- NO TABLE
SELECT DEPARTMENTID,MIN(SALARY), MAX (SALARY) FROM employeeS GROUP BY DEPARTMENTID
SELECT DEPARTMENTID,AVG(SALARY) FROM employeeS GROUP BY DEPARTMENTID
SELECT COUNT (*) DEPARTMENTID,AVG(SALARY) FROM employeeS GROUP BY DEPARTMENTID
SELECT NAME, AVG(PRICE) AS AVG_PRICE FROM PRODUCTS GROUP BY NAME HAVING AVG(PRICE)>100
SELECT PRODUCTID,COUNT (DISTINCT PRODUCTID) FROM SALES GROUP BY 
PRODUCTID HAVING COUNT (DISTINCT PRODUCTID)>100 ---SALES TABLE IS NOT GIVEN
SELECT * FROM SALES 
SELECT FORMAT (SALEDATE, 'YY-MM') AS SALEYEAR,COUNT (SALESID) AS COUNTID
FROM SALES GROUP BY FORMAT (SALEDATE, 'YY-MM')
SELECT *FROM Customers
SELECT LOCATION,COUNT (CUSTOMERID) FROM Customers GROUP BY Location
SELECT DepartmentID, SUM(SALARY) FROM Employees GROUP BY DepartmentID 
HAVING SUM(SALARY)>100000

SELECT * FROM Products
SELECT DISTINCT CATEGORY, AVG (PRICE*STOCKQUANTITY) FROM PRODUCTS 
GROUP BY Category HAVING AVG (PRICE*STOCKQUANTITY)>200
SELECT *FROM Employees
SELECT * FROM SALES
